### ISSUE TITLE
Investigate possible Http4s bug

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/pfps-shopping-cart#51]
It seems to happen when the authorization token is invalid / expired:

```scala
core 21:31:04.031 [ioapp-compute-2] ERROR org.http4s.server.service-errors - Error servicing request: POST /v1/cart from 127.0.0.1
core java.lang.ClassCastException: org.http4s.ContextRequest cannot be cast to org.http4s.AuthedRequest
core 	at cats.data.Kleisli.apply(Kleisli.scala:119)
core 	at org.http4s.server.package$AuthMiddleware$.$anonfun$apply$5(package.scala:122)
core 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
core 	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
core 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
core 	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
core 	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
core 	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:51)
core 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
core 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
core 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gvolpe** [comment]
Reported upstream https://github.com/http4s/http4s/issues/3100
