### ISSUE TITLE
java.lang.NumberFormatException: For input string: "0"uuid": "004b4457"

### ISSUE THREAD

**Issue by gantu** [gvolpe/pfps-shopping-cart#58]
Hi, 
I am getting very weird error, see below. I tried with different `SC_JWT_CLAIM` environment variable but I think it is not related to this variable. What can be the issue? 
The error is : 

```
java.lang.NumberFormatException: For input string: "0"uuid": "004b4457"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:776)
	at java.lang.Long.decode(Long.java:928)
	at java.util.UUID.fromString(UUID.java:198)
	at relay.effects.GenUUID$$anon$1.$anonfun$read$1(GenUUID.scala:28)
	at cats.ApplicativeError.catchNonFatal(ApplicativeError.scala:136)
	at cats.ApplicativeError.catchNonFatal$(ApplicativeError.scala:135)
	at cats.effect.IOLowPriorityInstances$IOEffect.catchNonFatal(IO.scala:767)
	at relay.effects.GenUUID$$anon$1.read(GenUUID.scala:28)
	at relay.modules.Security$.$anonfun$make$1(Security.scala:44)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by gvolpe** [comment]
Hi @gantu ,

Judging by that error you're not running the latest version, which updates exactly this part of the code.

Anyway, the error seems to be related to the value of `SC_JWT_CLAIM` not being a valid UUID, but it's more likely because it was hard-coded in the app (see https://github.com/gvolpe/pfps-shopping-cart/pull/55 for more details).

I will raise an issue to document the process of adding your own authentication data, that's something that has been missing :)

**Comment by gvolpe** [comment]
https://github.com/gvolpe/pfps-shopping-cart/issues/59

**Comment by gantu** [comment]
Hi, 
My bad. The issue is resolved. 
Thank you.
